Install Python header files, library and dev tools in Docker image
Moose introduced a dependency on the Python/C API with idaholab/moose#9887.
See build errors on casl-dev CDash server [here](http://casl-dev.ornl.gov/cdash/viewBuildError.php?buildid=289439):
```
bash: python-config: command not found
/scratch/vera_build/MOOSEExt/MOOSE/moose/framework/contrib/hit/hit.cpp:4:20: fatal error: Python.h: No such file or directory
```